name: Translate Readme

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@main
        with:
          node-version: '12.x'
      - name: Translate Readme - Latin
        uses: dephraiim/translate-readme@main
        with:
          LANG: la
      - name: Translate Readme - Chinese (Simplified)
        uses: dephraiim/translate-readme@main
        with:
          LANG: zh-CN

